"""empty message

Revision ID: 2c0d4bb1b2cb
Revises: c1b889c3fef2
Create Date: 2020-05-08 07:25:48.459064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c0d4bb1b2cb'
down_revision = 'c1b889c3fef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('questions_category_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'categories', ['category'], ['id'], onupdate='cascade', ondelete='set null')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_category_fkey', 'questions', 'categories', ['category'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
