"""empty message

Revision ID: 93373cbd6f1f
Revises: b2ca44b8bb51
Create Date: 2020-05-08 09:15:13.067762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93373cbd6f1f'
down_revision = 'b2ca44b8bb51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'answer',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('questions', 'difficulty',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questions', 'question',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'question',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('questions', 'difficulty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('questions', 'answer',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
